# Site settings
title: Andrew Thompson's IT Scrapbook
#email: ajthompson0659@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for sharing the things I've learned and don't want to forget.
  This blog features scraps of Linux, SDN, Cisco routing & switching, 
  and anything in between.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: ""
#github_username:  ajthompson0659

# Build settings
markdown: kramdown
